### ISSUE TITLE
There seems to be something strange with the angular velocity reported from the ship

### ISSUE THREAD

**Issue by molysgaard** [rfotino/space-ai#1]
Use the following code:

```
turn(1);
console.log(vel().angular);
```

Observe the ship as it spins. To my eye it seems as the ship spins considerably faster than the reported angular velocity.

**Comment by rfotino** [comment]
It might be easier to see if I added a "step" function so that you could step through one frame at a time. But `vel().angular` is in radians per frame, so for an angular velocity of 1 the ship should rotate almost 10 times per second (2π / 1 ≈ 6 frames per rotation, 60 frames per second / 6 frames per rotation = 10 rotations per second). Does it still seem faster than reported with that in mind?

**Comment by molysgaard** [comment]
No, that clears things up. This is inconsistent with the documentation though, where it is said that the vel().angular is in rad/sec.
Would be a lot easier for physical calculations if it was in rad/sec and not rad/frame.
It would also make sense if thrust() and turn() takes units in  pixels/(sec^2) and rad/(sec^2)

**Comment by rfotino** [comment]
Thanks for catching that, I've updated the documentation to be consistent. The unit of time shouldn't make a difference in physical calculations as long as it's consistent - you could consider each frame to be a "second" if you wanted to and then the simulation you're watching could be considered to just be a 60x speedup.
